
networks:
  localdev:
    name: localdev
services:
  api:
    build: PostsService/
    restart: always
    ports:
      - 8080:80
    depends_on:
      - sql-server
    networks:
      - localdev

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=MySQLPassw0rd
    ports:
      - 1433:1433
    networks:
      - localdev
